import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

import {
  compileProject,
  parseCompilerOptions,
  watchProject,
} from "../tools/wg/compile.mjs";
import { emitStoryModule } from "../tools/wg/compiler/emitter.js";
import { compileStorySources } from "../tools/wg/compiler/storyCompiler.js";

const FIXTURE_URL = new URL("./fixtures/wg/compiler.golden.wg", import.meta.url);
const GOLDEN_URL = new URL("./fixtures/wg/compiler.golden.json", import.meta.url);
const FIXTURE_FILE = "tests/fixtures/wg/compiler.golden.wg";

function withoutSourceLocations(value) {
  if (Array.isArray(value)) return value.map(withoutSourceLocations);
  if (!value || typeof value !== "object") return value;

  return Object.fromEntries(
    Object.entries(value)
      .filter(([key]) => key !== "source")
      .map(([key, child]) => [key, withoutSourceLocations(child)]),
  );
}

test("representative WG source compiles to the semantic golden bundle", async () => {
  const [source, expectedText] = await Promise.all([
    readFile(FIXTURE_URL, "utf8"),
    readFile(GOLDEN_URL, "utf8"),
  ]);
  const actual = withoutSourceLocations(
    compileStorySources([{ file: FIXTURE_FILE, source }]),
  );

  assert.deepEqual(actual, JSON.parse(expectedText));
});

test("generated WG modules are readable and retain source locations", () => {
  const bundle = {
    formatVersion: 1,
    scenes: {
      example: {
        id: "example",
        source: { file: "story/example.wg", line: 3, column: 1 },
      },
    },
    locationContributions: {},
    reminders: {},
    chats: {},
  };
  const output = emitStoryModule(bundle);

  assert.match(output, /^\/\/ Generated by tools\/wg\/compile\.mjs\. Do not edit\.\n/);
  assert.match(output, /export const WG_BUNDLE = \{\n  "formatVersion": 1,/);
  assert.match(output, /"source": \{\n        "file": "story\/example\.wg",/);
  assert.doesNotMatch(output, /const K=|const d=|encodedBundle/);
  assert.ok(output.endsWith("\n"));
});

test("checked-in project WG output is current", async () => {
  await assert.doesNotReject(() => compileProject({ check: true }));
});

test("compiler CLI accepts watch mode but not watch and check together", () => {
  assert.deepEqual(parseCompilerOptions(["--watch"]), {
    check: false,
    watch: true,
  });
  assert.throws(
    () => parseCompilerOptions(["--watch", "--check"]),
    /cannot be used together/,
  );
  assert.throws(
    () => parseCompilerOptions(["--wat"]),
    /Unknown compiler option: --wat/,
  );
});

test("watch mode builds initially, debounces WG changes, and survives errors", async () => {
  let notifyChange;
  let closed = false;
  let compileCount = 0;
  const messages = [];
  const errors = [];
  const fakeWatcher = {
    on() {},
    close() {
      closed = true;
    },
  };

  const controller = await watchProject({
    watch(_root, options, listener) {
      assert.deepEqual(options, { recursive: true });
      notifyChange = listener;
      return fakeWatcher;
    },
    async compile() {
      compileCount += 1;
      if (compileCount === 1) throw new Error("temporary source error");
      return { changed: false, checked: false };
    },
    debounceMs: 5,
    log: (message) => messages.push(message),
    logError: (message) => errors.push(message),
  });

  assert.equal(compileCount, 1);
  assert.match(errors[0], /temporary source error/);
  assert.match(messages.at(-1), /Watching story\/\*\*\/\*\.wg/);

  notifyChange("change", "school/events.wg");
  notifyChange("change", "school/events.wg");
  notifyChange("rename", "school/events.wg");
  await new Promise((resolve) => setTimeout(resolve, 30));

  assert.equal(compileCount, 2);
  assert.equal(messages.at(-1), "WG generated artifacts are unchanged.");

  controller.close();
  assert.equal(closed, true);
});
