export function emitStoryModule(bundle) {
  return [
    "// Generated by tools/wg/compile.mjs. Do not edit.",
    `export const WG_BUNDLE = ${JSON.stringify(bundle, null, 2)};`,
    "",
  ].join("\n");
}
