const EMPTY_ARRAY_DEFAULTS = new Set([
  "automaticTriggers",
  "conditions",
  "effects",
  "elseNodes",
  "filters",
  "locationTags",
  "onEnter",
  "passages",
  "placeKeys",
  "placeTags",
  "pools",
  "previews",
  "requirements",
  "responses",
  "tags",
]);
const NULL_DEFAULTS = new Set([
  "elseNodes",
  "heading",
  "hub",
  "hubText",
  "icon",
  "label",
  "next",
  "offer",
  "schoolClass",
  "system",
  "timeUntilPath",
  "warning",
  "when",
]);
const FALSE_DEFAULTS = new Set(["energyFree", "enterAfterTime"]);
const ZERO_DEFAULTS = new Set(["durationMinutes", "priority"]);
const ONE_DEFAULTS = new Set(["chance", "eventChance", "weight"]);
const TOP_LEVEL_COLLECTIONS = ["scenes", "sequences", "entries"];

function isOmittedDefault(key, value) {
  return (
    (value === null && NULL_DEFAULTS.has(key)) ||
    (value === false && FALSE_DEFAULTS.has(key)) ||
    (value === 0 && ZERO_DEFAULTS.has(key)) ||
    (value === 1 && ONE_DEFAULTS.has(key)) ||
    (Array.isArray(value) && value.length === 0 && EMPTY_ARRAY_DEFAULTS.has(key))
  );
}

function compactRuntimeValue(value) {
  if (Array.isArray(value)) return value.map(compactRuntimeValue);
  if (!value || typeof value !== "object") return value;

  return Object.fromEntries(
    Object.entries(value)
      .filter(([key, child]) => key !== "source" && !isOmittedDefault(key, child))
      .map(([key, child]) => [key, compactRuntimeValue(child)]),
  );
}

function createRuntimeBundle(bundle) {
  const runtimeBundle = compactRuntimeValue(bundle);
  for (const collectionName of TOP_LEVEL_COLLECTIONS) {
    for (const [id, definition] of Object.entries(runtimeBundle[collectionName])) {
      if (definition.id === id) delete definition.id;
    }
  }
  return runtimeBundle;
}

function collectKeyCounts(value, counts = new Map()) {
  if (Array.isArray(value)) {
    for (const item of value) collectKeyCounts(item, counts);
    return counts;
  }
  if (!value || typeof value !== "object") return counts;

  for (const [key, child] of Object.entries(value)) {
    counts.set(key, (counts.get(key) || 0) + 1);
    collectKeyCounts(child, counts);
  }
  return counts;
}

function createKeyTable(bundle) {
  const counts = collectKeyCounts(bundle);
  const originalKeys = new Set(counts.keys());
  const candidates = [...counts].sort(
    ([leftKey, leftCount], [rightKey, rightCount]) => {
      const leftLength = JSON.stringify(leftKey).length;
      const rightLength = JSON.stringify(rightKey).length;
      const leftBenefit = leftCount * (leftLength - 1) - leftLength;
      const rightBenefit = rightCount * (rightLength - 1) - rightLength;
      const keyOrder = leftKey < rightKey ? -1 : leftKey > rightKey ? 1 : 0;
      return rightBenefit - leftBenefit || keyOrder;
    },
  );
  const keys = [];
  const aliases = new Map();

  for (const [key, count] of candidates) {
    let alias = keys.length;
    // Leave holes for authored numeric keys so the runtime can distinguish them from aliases.
    while (originalKeys.has(String(alias))) {
      keys.push(null);
      alias = keys.length;
    }

    const keyLength = JSON.stringify(key).length;
    const aliasLength = String(alias).length;
    const payloadSavings = count * (keyLength - aliasLength);
    const tableCost = keyLength + 1;
    // A short key still has to pay for its full name once in the decoder table.
    if (payloadSavings <= tableCost) continue;

    aliases.set(key, String(alias));
    keys.push(key);
  }

  return { aliases, keys };
}

function encodeKeys(value, aliases) {
  if (Array.isArray(value)) return value.map((item) => encodeKeys(item, aliases));
  if (!value || typeof value !== "object") return value;

  return Object.fromEntries(
    Object.entries(value).map(([key, child]) => [
      aliases.get(key) ?? key,
      encodeKeys(child, aliases),
    ]),
  );
}

function stringifyJavaScript(value) {
  return JSON.stringify(value).replace(/"(0|[1-9]\d*)":/g, "$1:");
}

export function emitStoryModule(bundle) {
  const runtimeBundle = createRuntimeBundle(bundle);
  const { aliases, keys } = createKeyTable(runtimeBundle);
  const encodedBundle = encodeKeys(runtimeBundle, aliases);
  const decoder =
    'const d=v=>{if(Array.isArray(v))v.forEach(d);else if(v&&typeof v==="object")for(const n of Object.keys(v)){const x=v[n];d(x);const k=K[n]&&String(+n)===n?K[n]:n;if(k!==n){v[k]=x;delete v[n]}}return v};';
  const restoreIds =
    "for(const m of[B.scenes,B.sequences,B.entries])for(const i in m)m[i].id=i;";

  return [
    "// Generated by tools/wg/compile.mjs. Do not edit.",
    `const K=${JSON.stringify(keys)};${decoder}const B=d(${stringifyJavaScript(encodedBundle)});${restoreIds}export const WG_BUNDLE=B;`,
  ].join("\n");
}
