// worldgame/src/game/game.js
import { World } from "../world/world.js";
import { isPlaceUnlocked } from "../world/util/place.js";
import { Player } from "../player/player.js";
import { NPC } from "../npc/npc.js";
import {
  RandomStreams,
  deriveSeed,
  normalizeSeed,
  rollSeed,
} from "../../shared/util/random.js";
import { PLACE_TAGS } from "../../data/world/place.js";
import { NPC_REGISTRY } from "../../data/npc/npcs.js";
import { DEFAULT_NPC_INTERACTION_MINUTES } from "../../data/scene/actions.js";
import {
  INITIAL_PLAYER_AGE,
  PLAYER_ENERGY_DRAIN_PER_MINUTE,
  PLAYER_ENERGY_RECOVERY_PER_MINUTE,
} from "../../data/player/stats.js";
import {
  SaveValidationError,
  validateGameSave,
} from "./util/saveValidation.js";
import { buildGpsRoute, resolveNavigationDestination } from "./navigation.js";
import { authoredReminderId, getAuthoredReminder } from "./reminders.js";
import {
  addContact as addGameContact,
  createChatState,
  deliverDueChats,
  nextChatDeadline,
  startChat as startGameChat,
} from "./chat/runtime.js";
import {
  nextActiveTimerDeadline,
  processDueTimers,
  resyncTimers,
  restartTimer as restartGameTimer,
  startTimer as startGameTimer,
  stopTimer as stopGameTimer,
} from "./timers.js";
import {
  announcementDayKey,
  collectDailyAnnouncements,
  emptyDailyAnnouncements,
} from "./announcements.js";

export { SaveValidationError, validateGameSave };

const MS_PER_MINUTE = 60 * 1000;
const ENERGY_PRECISION = 1_000_000;

// High-level orchestrator for world + player + NPCs.
export class Game {
  constructor({
    seed = rollSeed(),
    startDate = new Date(),
    playerOptions = {},
    npcTemplates = NPC_REGISTRY.filter(
      (definition) => !definition.meta?.example,
    ),
  } = {}) {
    // --- deterministic random streams ---
    // `rnd` remains the general gameplay stream for callers that need one,
    // while engine subsystems use independent named streams.
    this.seed = normalizeSeed(seed);
    this.random = new RandomStreams(this.seed);
    this.rnd = this.getRNG("gameplay");

    // --- world ---
    this.world = new World({
      seed: deriveSeed(this.seed, "world"),
      startDate,
    });
    this.startedAt = this.now.toISOString();
    this.reminders = new Set();
    this.chats = createChatState();
    this.timers = {};

    // --- player ---
    this.player = new Player(playerOptions);
    this.player.setAgeAtDate(INITIAL_PLAYER_AGE, this.now);

    // --- story flags (separate from skills) ---
    this.flags = new Set();
    this.dailyFlags = new Set();
    this.story = {};
    this.currentStory = null;
    this.storyContinuations = [];
    this.storyRevision = 0;
    this.actionRevision = 0;
    this.interruptState = {
      active: null,
      pending: null,
      latchedSceneIds: [],
    };

    // --- npcs ---
    this.npcs = new Map();
    this._createNPCs(npcTemplates);
    this._initializeNPCBrains();

    // Player home (a Place instance generated by the map registry)
    const home = this._findFirstPlaceByKey("player_home");
    this.homeLocationId = home?.locationId ?? null;
    this.homePlaceId = home?.id ?? null;

    // Where is the player right now? Resolve location + place together so
    // we can never start "inside" a place belonging to another location.
    const hasStartLocation = playerOptions.startLocationId != null;
    const hasStartPlace = Object.prototype.hasOwnProperty.call(
      playerOptions,
      "startPlaceId",
    );

    if (
      hasStartLocation &&
      playerOptions.startLocationId != null &&
      !this.world.locations.has(playerOptions.startLocationId)
    ) {
      throw new Error(
        `Unknown starting location: ${playerOptions.startLocationId}`,
      );
    }

    this.currentLocationId = hasStartLocation
      ? playerOptions.startLocationId
      : (this.homeLocationId ?? this._pickDefaultLocationId());

    if (hasStartPlace) {
      // Explicit null means "start outside" and must not fall back home.
      this.currentPlaceId = playerOptions.startPlaceId;
    } else if (this.currentLocationId === this.homeLocationId) {
      this.currentPlaceId = this.homePlaceId;
    } else {
      this.currentPlaceId = null;
    }

    if (this.currentPlaceId != null) {
      const place = this._getPlaceById(
        this.currentLocationId,
        this.currentPlaceId,
      );
      if (!place) {
        throw new Error(
          `Unknown starting place '${this.currentPlaceId}' in location '${this.currentLocationId}'`,
        );
      }
      this.currentPlaceId = place.id;
      this.currentPlaceKey = place.key ?? null;
    } else {
      this.currentPlaceKey = null;
    }

    // Phone GPS navigation. The generated place id and its containing
    // location are persisted together so corrupt targets fail validation.
    this.gpsTarget = null;

    // Simple log of actions for debugging / history
    this.log = [];

    // simple event system for UI / other systems to subscribe
    this._listeners = {
      time: new Set(), // (game, minutes) => void
      timeJump: new Set(), // (game, { from, to, minutes, mode, source }) => void
      location: new Set(), // (game, newLocationId) => void
    };

    // A new game starts partway through its first day, so seed the same batch
    // that a midnight crossing would have created for that date.
    this.dailyAnnouncements = collectDailyAnnouncements(this, this.now);
  }

  // --------------------------
  // Basic getters
  // --------------------------
  get now() {
    return this.world.time.toDate();
  }

  get location() {
    return this.world.getLocation(this.currentLocationId);
  }

  get currentPlace() {
    if (!this.currentPlaceId) return null;
    const loc = this.location;
    return (
      (loc?.places || []).find((p) => p.id === this.currentPlaceId) || null
    );
  }

  get npcsArray() {
    return [...this.npcs.values()];
  }

  /** Return a stable named RNG stream derived from this game's master seed. */
  getRNG(name = "gameplay") {
    return this.random.stream(name);
  }

  addContact(npcId) {
    return addGameContact(this, npcId);
  }

  startChat(chatId) {
    return startGameChat(this, chatId);
  }

  // --------------------------
  // Time & actions
  // --------------------------
  /**
   * Advance world time by N minutes and exactly simulate intervening NPC decisions.
   */
  advanceMinutes(mins, { drainPlayerEnergy = true } = {}) {
    const amount = Number(mins);
    if (!Number.isFinite(amount) || amount <= 0) {
      throw new TypeError(
        `Game.advanceMinutes requires positive minutes: ${String(mins)}`,
      );
    }
    if (typeof drainPlayerEnergy !== "boolean") {
      throw new TypeError(
        "Game.advanceMinutes drainPlayerEnergy must be a boolean",
      );
    }

    const target = new Date(this.now.getTime() + amount * MS_PER_MINUTE);
    return this._changeTimeTo(target, {
      mode: "simulate",
      source: "advance",
      drainPlayerEnergy,
    });
  }

  /**
   * Move to an absolute timestamp. The default resync mode discards skipped NPC
   * micro-history and reconstructs a coherent destination state. Use
   * { mode: "simulate" } when every intervening decision must be processed.
   */
  jumpToDate(value, { mode = "resync" } = {}) {
    const target =
      value instanceof Date ? new Date(value.getTime()) : new Date(value);
    if (!Number.isFinite(target.getTime())) {
      throw new Error(`Invalid jump date: ${value}`);
    }
    if (mode !== "resync" && mode !== "simulate") {
      throw new Error(`Unknown time jump mode: ${mode}`);
    }

    return this._changeTimeTo(target, {
      mode,
      source: "jump",
      drainPlayerEnergy: true,
    });
  }

  _changeTimeTo(target, options) {
    // Scheduled boundaries must observe their own world state, even during a long rest.
    // Resync/debug jumps remain observational and do not manufacture skipped events.
    const firstDeadline = Math.min(
      nextChatDeadline(this),
      nextActiveTimerDeadline(this),
    );
    if (
      options.mode !== "simulate" ||
      target <= this.now ||
      firstDeadline > target.getTime()
    ) {
      return this._changeTimeStep(target, options);
    }
    const from = new Date(this.now);
    let ejectedFrom = null;
    let boundaries = 0;
    while (true) {
      const deadlineMs = Math.min(
        nextChatDeadline(this),
        nextActiveTimerDeadline(this),
      );
      if (deadlineMs > target.getTime()) break;
      if (++boundaries > 10000) {
        throw new Error("Scheduled event limit exceeded during one time advance");
      }
      const deadline = new Date(Math.max(this.now.getTime(), deadlineMs));
      if (deadline > this.now) {
        const change = this._changeTimeStep(deadline, options);
        ejectedFrom ||= change.ejectedFrom;
      }
      processDueTimers(this);
      deliverDueChats(this);
    }
    if (target > this.now) {
      const change = this._changeTimeStep(target, options);
      ejectedFrom ||= change.ejectedFrom;
    }
    return {
      from,
      to: new Date(this.now),
      minutes: (this.now - from) / MS_PER_MINUTE,
      ...options,
      ejectedFrom,
    };
  }

  _changeTimeStep(target, { mode, source, drainPlayerEnergy }) {
    const from = new Date(this.now.getTime());
    const to = new Date(target.getTime());
    const minutes = (to.getTime() - from.getTime()) / MS_PER_MINUTE;

    if (mode === "simulate" && minutes < 0) {
      throw new RangeError(
        "Simulated time changes cannot run backwards; use resync mode",
      );
    }

    if (minutes === 0) {
      return { from, to, minutes, mode, source, drainPlayerEnergy };
    }

    let ejectedFrom = null;

    if (mode === "simulate") {
      this.world.advance(minutes);

      // Brains resolve meaningful decision boundaries, not every minute.
      for (const npc of this.npcs.values()) {
        npc.brain?.updateTo(this.now, this);
      }
    } else {
      this.world.setDate(to);

      for (const npc of this.npcs.values()) {
        npc.brain?.resyncAt(this.now, this);
      }
      if (to > from) resyncTimers(this, to);
    }

    this._applyElapsedPlayerChanges(minutes, {
      drainEnergy: drainPlayerEnergy,
    });
    this._clearDailyFlagsAfterMidnight(from, this.now);
    ejectedFrom = this._enforcePlaceClosing(from, this.now);
    this._syncDailyAnnouncementsAfterDateChange(from, this.now);

    const change = {
      from,
      to: new Date(this.now.getTime()),
      minutes,
      mode,
      source,
      drainPlayerEnergy,
      ejectedFrom,
    };

    if (mode === "simulate") {
      // Normal time listeners are reserved for genuinely simulated elapsed time.
      this._dispatchListeners("time", [this, minutes, change]);
    } else {
      // A resync is observational: skipped wages, encounters, deliveries, etc.
      // must not be inferred from the size of this delta.
      this._dispatchListeners("timeJump", [this, change]);
    }

    return change;
  }

  _applyElapsedPlayerChanges(minutes, { drainEnergy = true } = {}) {
    this.player.syncAgeAt(this.now);
    if (minutes <= 0 || !drainEnergy) return;

    const energy = this.player.adjustStatBase(
      "energy",
      -minutes * PLAYER_ENERGY_DRAIN_PER_MINUTE,
    );
    // Keep one large advance identical to many minute-sized advances.
    this.player.setStatBase(
      "energy",
      Math.round(energy * ENERGY_PRECISION) / ENERGY_PRECISION,
    );
  }

  _clearDailyFlagsAfterMidnight(from, to) {
    if (!(to > from)) return;
    const sameUtcDay =
      from.getUTCFullYear() === to.getUTCFullYear() &&
      from.getUTCMonth() === to.getUTCMonth() &&
      from.getUTCDate() === to.getUTCDate();
    if (!sameUtcDay) this.dailyFlags.clear();
  }

  _syncDailyAnnouncementsAfterDateChange(from, to) {
    if (announcementDayKey(from) === announcementDayKey(to)) return;

    this.dailyAnnouncements =
      to > from
        ? collectDailyAnnouncements(this, to)
        : emptyDailyAnnouncements(to);
  }

  _enforcePlaceClosing(from, to) {
    const place = this.currentPlace;
    if (!place?.props?.ejectAtClose || !(to > from)) return null;

    const closingTime = place.getClosingTime?.(from) ?? null;
    const crossedClosingTime = closingTime && to >= closingTime;
    const alreadyClosed = typeof place.isOpen === "function" && !place.isOpen(from);
    if (!crossedClosingTime && !alreadyClosed) return null;

    const ejectedFrom = {
      id: String(place.id),
      key: place.key == null ? null : String(place.key),
      name: place.name,
      closedAt: closingTime?.toISOString?.() ?? null,
    };
    this.setCurrentPlace();
    return ejectedFrom;
  }

  /**
   * Move player to another location on the world map.
   */
  moveTo(locationId, { preserveStory = false } = {}) {
    if (!this.world.locations.has(locationId)) {
      throw new Error(`Unknown location: ${locationId}`);
    }
    if (locationId === this.currentLocationId) return;

    this.currentLocationId = locationId;
    // When moving, you're typically not inside any specific place
    this.currentPlaceId = null;
    this.currentPlaceKey = null;
    if (!preserveStory) this._clearStory();
    if (
      this.gpsTarget &&
      String(this.gpsTarget.locationId) === String(this.currentLocationId)
    ) {
      this.gpsTarget = null;
    }

    // Subscribers should observe a fully consistent position.
    this._dispatchListeners("location", [this, locationId]);
  }

  /**
   * Set where inside the location the player currently is.
   * Use a Place.id, or pass null and set currentPlaceKey to something virtual like "street".
   */
  setCurrentPlace({
    placeId = null,
    placeKey = null,
    preserveStory = false,
  } = {}) {
    if (placeId == null) {
      this.currentPlaceId = null;
      this.currentPlaceKey = placeKey == null ? null : String(placeKey);
      if (!preserveStory) this._clearStory();
      return;
    }

    const place = this._getPlaceById(this.currentLocationId, placeId);
    if (!place) {
      throw new Error(
        `Unknown place '${placeId}' in location '${this.currentLocationId}'`,
      );
    }
    if (!isPlaceUnlocked(place)) {
      throw new Error("That place has not been unlocked");
    }

    if (placeKey != null && String(placeKey) !== String(place.key ?? "")) {
      throw new Error(
        `Place key '${placeKey}' does not match place '${placeId}' (${place.key ?? "no key"})`,
      );
    }

    // Concrete places always use their canonical registry key. Virtual
    // place keys are represented only by { placeId: null, placeKey: ... }.
    this.currentPlaceId = place.id;
    this.currentPlaceKey = place.key ?? null;
    if (!preserveStory) this._clearStory();
  }

  _clearStory() {
    if (this.currentStory === null && this.storyContinuations.length === 0) return;
    this.currentStory = null;
    this.storyContinuations.length = 0;
    this.storyRevision += 1;
  }

  // --- Story flags ---
  setFlag(flag, value = true) {
    const key = String(flag);
    if (value) this.flags.add(key);
    else this.flags.delete(key);
  }
  clearFlag(flag) {
    this.flags.delete(String(flag));
  }
  hasFlag(flag) {
    return this.flags.has(String(flag));
  }

  /** Reveal every generated instance with this registry key. */
  unlockPlacesByKey(placeKey) {
    const key = String(placeKey ?? "");
    if (!key) throw new TypeError("Unlocking places requires a place key");

    let unlocked = 0;
    for (const location of this.world.locations.values()) {
      for (const place of location.places || []) {
        if (String(place.key) === key && place.unlock()) unlocked += 1;
      }
    }
    return unlocked;
  }

  /** Move the player immediately for an authored story effect. */
  relocatePlayer(destination) {
    if (!destination || typeof destination !== "object") {
      throw new TypeError("Player relocation requires a destination");
    }

    let target = null;
    if (destination.kind === "home") {
      target = {
        locationId: this.homeLocationId,
        placeId: this.homePlaceId,
      };
    } else if (destination.kind === "nearest-place") {
      const placeKey = String(destination.placeKey || "");
      target = this.world.map.findNearestPlace(
        (place) => String(place.key) === placeKey && isPlaceUnlocked(place),
        this.currentLocationId,
        this.now,
        false,
      );
    } else {
      throw new Error(`Unknown player relocation kind '${String(destination.kind)}'`);
    }

    if (!target?.locationId || !target?.placeId) {
      throw new Error("No valid player relocation destination was found");
    }
    const place = this._getPlaceById(target.locationId, target.placeId);
    if (!place || !isPlaceUnlocked(place)) {
      throw new Error("Player relocation destination is unavailable");
    }

    if (String(target.locationId) !== String(this.currentLocationId)) {
      this.moveTo(target.locationId, { preserveStory: true });
    }
    this.setCurrentPlace({ placeId: target.placeId, preserveStory: true });
    return {
      locationId: String(target.locationId),
      placeId: String(target.placeId),
      placeKey: String(place.key),
    };
  }

  // --- Daily flags (cleared after crossing UTC midnight) ---
  setDailyFlag(flag, value = true) {
    const key = String(flag);
    if (value) this.dailyFlags.add(key);
    else this.dailyFlags.delete(key);
  }
  clearDailyFlag(flag) {
    this.dailyFlags.delete(String(flag));
  }
  hasDailyFlag(flag) {
    return this.dailyFlags.has(String(flag));
  }

  /** Activate authored content once; automatic reminders cannot be manually added. */
  addReminder(id) {
    if (!getAuthoredReminder(id)) throw new Error(`Unknown authored reminder '${String(id)}'`);
    this.reminders.add(id);
  }

  /** Also remove pending text if a post-time story effect resolves this reminder. */
  clearReminder(id) {
    if (!getAuthoredReminder(id)) throw new Error(`Unknown authored reminder '${String(id)}'`);
    this.reminders.delete(id);
    const itemId = authoredReminderId(id);
    this.dailyAnnouncements.items = this.dailyAnnouncements.items.filter((item) => item.id !== itemId);
  }

  /** Start a named timer without moving an existing deadline. */
  startTimer(id) {
    return startGameTimer(this, id);
  }

  /** Replace a named timer with a fresh schedule from the current world time. */
  restartTimer(id) {
    return restartGameTimer(this, id);
  }

  /** Stop a named timer. Unknown timer definitions are programmer errors. */
  stopTimer(id) {
    return stopGameTimer(this, id);
  }

  /** Dismiss the visible batch without changing its source reminders. */
  dismissDailyAnnouncements() {
    const dismissed = this.dailyAnnouncements.items.length;
    if (dismissed > 0) {
      this.dailyAnnouncements = emptyDailyAnnouncements(this.now);
    }
    return dismissed;
  }

  // --- Phone GPS navigation ---
  setGpsTarget(placeId) {
    const destination = resolveNavigationDestination(this, placeId);
    if (!destination) {
      throw new Error(`Unknown GPS destination: ${String(placeId)}`);
    }

    if (destination.locationId === String(this.currentLocationId)) {
      this.gpsTarget = null;
      return { active: false, alreadyThere: true, destination };
    }

    const route = this.world.map.getTravelTotal(
      this.currentLocationId,
      destination.locationId,
    );
    if (!route) {
      throw new Error(`No route to GPS destination '${destination.name}'`);
    }

    this.gpsTarget = {
      placeId: destination.placeId,
      locationId: destination.locationId,
    };
    return { active: true, alreadyThere: false, route: this.getGpsRoute() };
  }

  clearGpsTarget() {
    const wasActive = this.gpsTarget !== null;
    this.gpsTarget = null;
    return wasActive;
  }

  getGpsRoute() {
    return buildGpsRoute(this);
  }

  // --- Convenience queries ---
  getNPCsAtLocation(locationId = this.currentLocationId) {
    const id = String(locationId);
    return this.npcsArray.filter((n) => String(n.locationId) === id);
  }

  /** Return NPCs sharing the player's exact outdoor or indoor position. */
  getNPCsAtCurrentPosition() {
    const locationId = String(this.currentLocationId);
    const placeId =
      this.currentPlaceId == null ? null : String(this.currentPlaceId);
    return this.npcsArray.filter(
      (npc) =>
        String(npc.locationId) === locationId &&
        (npc.currentPlaceId == null ? null : String(npc.currentPlaceId)) ===
          placeId,
    );
  }

  /** Resolve whether an NPC can stop for an interaction right now. */
  getNPCInteractionAccess(
    npcOrId,
    { at = this.now, durationMinutes = DEFAULT_NPC_INTERACTION_MINUTES } = {},
  ) {
    const date = at instanceof Date ? new Date(at.getTime()) : new Date(at);
    const duration = Number(durationMinutes);
    if (!Number.isFinite(date.getTime())) {
      throw new TypeError("NPC interaction access requires a valid date");
    }
    if (!Number.isFinite(duration) || duration < 0) {
      throw new TypeError(
        "NPC interaction duration must be a non-negative number",
      );
    }

    const npc =
      npcOrId && typeof npcOrId === "object"
        ? npcOrId
        : this.npcs.get(String(npcOrId));
    if (!npc || this.npcs.get(String(npc.id)) !== npc) {
      return { allowed: false, code: "unknown-npc", npc: null };
    }

    if (!this.getNPCsAtCurrentPosition().includes(npc)) {
      return { allowed: false, code: "not-here", npc };
    }

    if (npc.brain?.isBusyWithObligation) {
      return { allowed: false, code: "busy-obligation", npc };
    }

    const conflict = npc.brain?.getInteractionObligationConflict?.(this, {
      at: date,
      durationMinutes: duration,
    });
    if (conflict) {
      return {
        allowed: false,
        code: "obligation-deadline",
        npc,
        conflict,
      };
    }

    return { allowed: true, code: "allowed", npc };
  }

  /** Resolve whether the player may enter a place at a specific time. */
  getPlaceAccess(placeOrId, { at = this.now } = {}) {
    if (!(at instanceof Date) || !Number.isFinite(at.getTime())) {
      throw new TypeError("Game.getPlaceAccess requires a valid Date");
    }

    if (this.currentPlaceId != null) {
      return {
        allowed: false,
        code: "already-inside",
        place: null,
      };
    }

    const placeId =
      placeOrId && typeof placeOrId === "object" ? placeOrId.id : placeOrId;
    const place = this._getPlaceById(this.currentLocationId, placeId);
    if (!place) {
      return {
        allowed: false,
        code: "not-here",
        place: null,
      };
    }

    if (!isPlaceUnlocked(place)) {
      return {
        allowed: false,
        code: "locked",
        place: null,
      };
    }

    const ageRange = place.props?.ages;
    const playerAge = this.player.getAgeAt(at);
    if (ageRange?.min != null && playerAge < ageRange.min) {
      return {
        allowed: false,
        code: "age-minimum",
        place,
        requiredAge: ageRange.min,
      };
    }
    if (ageRange?.max != null && playerAge > ageRange.max) {
      return {
        allowed: false,
        code: "age-maximum",
        place,
        requiredAge: ageRange.max,
      };
    }

    if (typeof place.isOpen === "function" && !place.isOpen(at)) {
      return {
        allowed: false,
        code: "closed",
        place,
      };
    }

    return { allowed: true, code: "allowed", place };
  }

  /**
   * Wrapper for player actions: do stuff, spend time, log it.
   */
  runAction({
    label,
    minutes = 0,
    energyFree = false,
    resting = false,
    apply,
    after,
    interrupt,
  }) {
    let amount = 0;
    if (minutes !== 0) {
      amount = Number(minutes);
      if (!Number.isFinite(amount) || amount <= 0) {
        throw new TypeError(
          `runAction requires positive minutes: ${String(minutes)}`,
        );
      }
    }
    if (typeof energyFree !== "boolean") {
      throw new TypeError("runAction energyFree must be a boolean");
    }
    if (typeof resting !== "boolean") {
      throw new TypeError("runAction resting must be a boolean");
    }
    if (resting && !energyFree) {
      throw new TypeError("runAction resting actions must be energy-free");
    }

    const startedAt = this.now.toISOString();
    let timeChange = null;
    // Any completed player action acknowledges the currently visible batch.
    // If this action crosses midnight, time synchronization creates a fresh
    // batch for the destination day later in this action.
    this.dismissDailyAnnouncements();

    if (typeof apply === "function") {
      apply(this);
    }

    if (resting && amount > 0) {
      const energy = this.player.adjustStatBase(
        "energy",
        amount * PLAYER_ENERGY_RECOVERY_PER_MINUTE,
      );
      this.player.setStatBase(
        "energy",
        Math.round(energy * ENERGY_PRECISION) / ENERGY_PRECISION,
      );
    }

    if (amount > 0) {
      timeChange = this.advanceMinutes(amount, {
        drainPlayerEnergy: !energyFree,
      });
    }

    const skipAfter = typeof interrupt === "function"
      ? interrupt(this, "before-after", timeChange) === true
      : false;

    // Arrival/event resolution belongs after time simulation so it observes
    // the destination clock and final NPC positions.
    if (!skipAfter && typeof after === "function") {
      after(this);
    }

    if (typeof interrupt === "function") {
      interrupt(this, "after-after", timeChange);
    }

    // Successful actions advance the deterministic choice-roll epoch.
    // Rendering and rejected requests do not.
    this.actionRevision += 1;

    // A log entry describes a completed action, so add it only after its
    // effects, time cost, and post-time resolution have succeeded.
    if (typeof label === "string" && label) {
      this.log.push({ t: startedAt, label });
    }
    return { timeChange };
  }

  _dispatchListeners(eventName, args) {
    for (const callback of this._listeners[eventName]) callback(...args);
  }

  // --------------------------
  // Simple event/listener API
  // --------------------------
  /**
   * game.on("time", cb) -> unsubscribe function
   * game.on("timeJump", cb)
   * game.on("location", cb)
   */
  on(eventName, fn) {
    const set = this._listeners[eventName];
    if (!set) throw new Error(`Unknown event type: ${eventName}`);
    set.add(fn);
    return () => set.delete(fn);
  }

  // --------------------------
  // Save / load
  // --------------------------
  toJSON() {
    return {
      saveVersion: 32,
      seed: this.seed,
      random: this.random.toJSON(),
      time: this.now.toISOString(),
      startedAt: this.startedAt,
      reminders: [...this.reminders].sort(),
      chats: JSON.parse(JSON.stringify(this.chats)),
      timers: JSON.parse(JSON.stringify(this.timers)),
      world: this.world.toJSON(),
      player: this.player.toJSON(),
      npcs: this.npcsArray.map((npc) => npc.toJSON()),
      homeLocationId: this.homeLocationId,
      homePlaceId: this.homePlaceId,
      currentLocationId: this.currentLocationId,
      currentPlaceId: this.currentPlaceId,
      currentPlaceKey: this.currentPlaceKey,
      gpsTarget: this.gpsTarget === null ? null : { ...this.gpsTarget },
      flags: [...this.flags],
      dailyFlags: [...this.dailyFlags],
      dailyAnnouncements: JSON.parse(JSON.stringify(this.dailyAnnouncements)),
      story: JSON.parse(JSON.stringify(this.story)),
      currentStory:
        this.currentStory === null
          ? null
          : JSON.parse(JSON.stringify(this.currentStory)),
      storyContinuations: JSON.parse(JSON.stringify(this.storyContinuations)),
      storyRevision: this.storyRevision,
      actionRevision: this.actionRevision,
      interruptState: JSON.parse(JSON.stringify(this.interruptState)),
      log: this.log.map((entry) => ({ ...entry })),
    };
  }

  static fromJSON(data) {
    validateGameSave(data);

    const savedStartDate = data.world.time.date;

    // Construct only the runtime shell. Most constructor-generated state is
    // replaced below during hydration.
    const game = new Game({
      seed: data.seed,
      startDate: new Date(savedStartDate),
      playerOptions: {},
      npcTemplates: [],
    });

    game.random = RandomStreams.fromJSON(data.random);
    game.rnd = game.getRNG("gameplay");
    game.world = World.fromJSON(data.world);
    game.startedAt = data.startedAt;
    game.reminders = new Set(data.reminders);
    game.chats = JSON.parse(JSON.stringify(data.chats));
    game.timers = JSON.parse(JSON.stringify(data.timers));

    game.player = Player.fromJSON(data.player || {});
    game.player.syncAgeAt(game.now);

    game.npcs = new Map();
    for (const npcData of Array.isArray(data.npcs) ? data.npcs : []) {
      const npc = NPC.fromJSON(npcData);
      const id = String(npc.id || npc.name);
      npc.id = id;
      game.npcs.set(id, npc);
    }

    game.homeLocationId = data.homeLocationId;
    game.homePlaceId = data.homePlaceId;
    game.currentLocationId = data.currentLocationId;
    game.currentPlaceId = data.currentPlaceId;
    game.currentPlaceKey = data.currentPlaceKey;
    game.gpsTarget = data.gpsTarget === null ? null : { ...data.gpsTarget };
    game.flags = new Set(data.flags);
    game.dailyFlags = new Set(data.dailyFlags);
    game.dailyAnnouncements = JSON.parse(JSON.stringify(data.dailyAnnouncements));
    game.story = JSON.parse(JSON.stringify(data.story));
    game.currentStory =
      data.currentStory === null
        ? null
        : JSON.parse(JSON.stringify(data.currentStory));
    game.storyContinuations = JSON.parse(JSON.stringify(data.storyContinuations));
    game.storyRevision = data.storyRevision;
    game.actionRevision = data.actionRevision;
    game.interruptState = JSON.parse(JSON.stringify(data.interruptState));
    game.log = data.log.map((entry) => ({ ...entry }));

    game._initializeNPCBrains();

    return game;
  }

  _initializeNPCBrains() {
    for (const npc of this.npcs.values()) {
      npc.brain?.initialize(this, this.now);
    }
  }

  _pickDefaultLocationId() {
    const first = this.world.locations.keys().next();
    return first.done ? null : first.value;
  }

  _findFirstPlaceByKey(placeKey) {
    const key = String(placeKey);
    for (const loc of this.world.locations.values()) {
      for (const p of loc.places || []) {
        if (p?.key === key) return p;
      }
    }
    return null;
  }

  _getPlaceKeyById(locationId, placeId) {
    const place = this._getPlaceById(locationId, placeId);
    return place?.key ?? null;
  }

  _getPlaceById(locationId, placeId) {
    if (placeId == null) return null;
    const loc = this.world.getLocation(locationId);
    return (loc?.places || []).find((p) => p.id === placeId) || null;
  }

  // --------------------------
  // Internals
  // --------------------------
  _createNPCs(templates) {
    for (const def of templates || []) {
      let npc;
      let id;

      if (def instanceof NPC) {
        npc = def;
        id = def.id || def.name;
      } else {
        npc = new NPC(def);
        id = def.id || npc.id || npc.name;
      }

      // Ensure id is always a string
      id = String(id || npc.name);
      npc.id = id;

      // Attach home + starting location
      this._assignHomeForNPC(id, npc);

      this.npcs.set(id, npc);
    }
  }

  /**
   * Assign a unique home Location + create a unique home Place for an NPC
   * based on npc.homePreference.
   *
   * homePreference supports selecting ONE strategy at random from:
   *  - withKey: pick random location that already contains any Place.key in the list
   *  - withPlaceCategory: pick location with the most places whose props.category matches any tag
   *  - withLocationCategory: pick location with the most location.tags matches
   *
   * nameFn(chosenLocation) is used to name the created home Place.
   */
  _assignHomeForNPC(id, npc) {
    const rnd = this.getRNG("npc-homes");
    const pref = npc?.homePreference;
    if (!pref) {
      throw new Error(`NPC '${id}' has no homePreference`);
    }

    const strategies = [];
    if (Array.isArray(pref.withKey) && pref.withKey.length) {
      strategies.push({ kind: "withKey", values: pref.withKey });
    }
    if (
      Array.isArray(pref.withPlaceCategory) &&
      pref.withPlaceCategory.length
    ) {
      strategies.push({
        kind: "withPlaceCategory",
        values: pref.withPlaceCategory,
      });
    }
    if (
      Array.isArray(pref.withLocationCategory) &&
      pref.withLocationCategory.length
    ) {
      strategies.push({
        kind: "withLocationCategory",
        values: pref.withLocationCategory,
      });
    }

    if (!strategies.length) {
      throw new Error(
        `homePreference for NPC '${id}' must include at least one of withKey, withPlaceCategory, withLocationCategory`,
      );
    }

    const pick = strategies[(rnd() * strategies.length) | 0];
    const allLocations = [...this.world.locations.values()];
    if (!allLocations.length) throw new Error("World has no locations");

    const pickRandom = (arr) => arr[(rnd() * arr.length) | 0];

    const placeHasAnyCategory = (place, wantedSet) => {
      const cat = place?.props?.category;
      if (!cat) return false;
      const cats = Array.isArray(cat) ? cat : [cat];
      for (const c of cats) if (wantedSet.has(c)) return true;
      return false;
    };

    let chosenLocation = null;

    if (pick.kind === "withKey") {
      const wantedKeys = new Set(pick.values.map(String));
      const candidates = allLocations.filter((loc) =>
        (loc.places || []).some((p) => wantedKeys.has(String(p.key))),
      );
      if (!candidates.length) {
        throw new Error(
          `No location contains any place with key in [${[...wantedKeys].join(", ")}]`,
        );
      }
      chosenLocation = pickRandom(candidates);
    }

    if (pick.kind === "withPlaceCategory") {
      const wanted = new Set(pick.values);
      let bestScore = -1;
      let best = [];

      for (const loc of allLocations) {
        let score = 0;
        for (const pl of loc.places || []) {
          if (placeHasAnyCategory(pl, wanted)) score++;
        }

        if (score > bestScore) {
          bestScore = score;
          best = [loc];
        } else if (score === bestScore) {
          best.push(loc);
        }
      }

      if (bestScore <= 0) {
        throw new Error(
          `No location has any places with category in [${[...wanted].join(", ")}]`,
        );
      }
      chosenLocation = pickRandom(best);
    }

    if (pick.kind === "withLocationCategory") {
      const wanted = new Set(pick.values);
      let bestScore = -1;
      let best = [];

      for (const loc of allLocations) {
        const tags = Array.isArray(loc.tags) ? loc.tags : [];
        let score = 0;
        for (const t of tags) if (wanted.has(t)) score++;

        if (score > bestScore) {
          bestScore = score;
          best = [loc];
        } else if (score === bestScore) {
          best.push(loc);
        }
      }

      if (bestScore <= 0) {
        throw new Error(
          `No location has any tags in [${[...wanted].join(", ")}]`,
        );
      }
      chosenLocation = pickRandom(best);
    }

    if (!chosenLocation) {
      throw new Error(`Failed to choose a home location for NPC '${id}'`);
    }

    // Create a unique home Place at the chosen location
    const homeId = `home_${id}`;
    const displayName =
      typeof pref.nameFn === "function"
        ? pref.nameFn(chosenLocation)
        : `${npc.name}'s home`;

    const homePlace = this.world.createPlaceAt(
      {
        id: homeId,
        key: homeId,
        name: displayName,
        unlocked: false,
        props: {
          category: [PLACE_TAGS.housing],
          ownerNpcId: id,
          isResidence: true,
          discovered: false,
          icon: "🏠",
        },
      },
      chosenLocation.id,
    );

    npc.homeLocationId = String(chosenLocation.id);
    npc.homePlaceId = homePlace ? homePlace.id : homeId;

    // Start NPC at home by default
    if (!npc.locationId) {
      npc.setLocationAndPlace(String(chosenLocation.id), npc.homePlaceId);
    }
  }
}
