// worldgame/src/game/game.js
import { World, Player, NPC } from "../classes.js";
import { makeRNG } from "../../shared/modules.js";
import { PLACE_TAGS, NPC_REGISTRY } from "../../data/data.js";
import { Localizer, SceneManager } from "./module.js";
import { SCENE_DEFS } from "../../data/scenes/index.js";

// High-level orchestrator for world + player + NPCs.
export class Game {
    constructor({
        seed = Date.now(),
        startDate = new Date(),
        playerOptions = {},
        npcTemplates = NPC_REGISTRY,
        strings = null,
        scenes = SCENE_DEFS,
        // SceneManager: first scene shown on start (first update)
        defaultSceneId = null,
        // SceneManager: shown when next scene can't be resolved
        fallbackSceneId = null,
        // If false, scenes will not resolve until game.startGame() is called.
        autoStartScenes = true,
    } = {}) {
        // --- core random seed ---
        this.seed = seed >>> 0;
        this.rnd = makeRNG(this.seed);

        // --- world ---
        this.world = new World({
            rnd: this.rnd,
            startDate,
        });

        // --- player ---
        this.player = new Player(playerOptions);

        // --- story flags (separate from skills) ---
        this.flags = new Set();

        // --- localisation ---
        this.localizer = new Localizer(strings);

        // --- npcs ---
        this.npcs = new Map();
        this._createNPCs(npcTemplates);
        this._initializeNPCBrains();

        // Player home (a Place instance generated by the map registry)
        const home = this._findFirstPlaceByKey("player_home");
        this.homeLocationId = home?.locationId ?? null;
        this.homePlaceId = home?.id ?? null;

        // Where is the player right now?
        this.currentLocationId =
            playerOptions.startLocationId || this.homeLocationId || this._pickDefaultLocationId();

        // Optional: which *place* inside the location (or a virtual key like "street")
        this.currentPlaceId = playerOptions.startPlaceId ?? this.homePlaceId ?? null;
        this.currentPlaceKey = this._getPlaceKeyById(this.currentLocationId, this.currentPlaceId);

        // For later: currently active “event/scene”
        this.currentScene = null;

        // Simple log of actions for debugging / history
        this.log = [];

        // simple event system for UI / other systems to subscribe
        this._listeners = {
            time: new Set(), // (game, minutes) => void
            location: new Set(), // (game, newLocationId) => void
            scene: new Set(), // (game, sceneOrNull) => void
        };

        // --- scenes ---
        this.sceneManager = new SceneManager({
            game: this,
            scenes,
            localizer: this.localizer,
            rnd: this.rnd,
            defaultSceneId,
            fallbackSceneId,
            autoStart: autoStartScenes,
        });

        if (autoStartScenes) this.startGame();
    }

    // --------------------------
    // Basic getters
    // --------------------------
    get now() {
        return this.world.time.date;
    }

    get location() {
        return this.world.getLocation(this.currentLocationId);
    }

    get currentPlace() {
        if (!this.currentPlaceId) return null;
        const loc = this.location;
        return (loc?.places || []).find((p) => p.id === this.currentPlaceId) || null;
    }

    get npcsArray() {
        return [...this.npcs.values()];
    }

    // --------------------------
    // Time & actions
    // --------------------------
    /**
     * Advance world time by N minutes.
     * Later this is where you'll hook NPC AI, queued events, etc.
     */
    advanceMinutes(mins) {
        if (!Number.isFinite(mins) || mins <= 0) return;

        this.world.advance(mins);

        // NPC brains resolve only meaningful decision points between their last
        // update and the new world time; no minute-by-minute schedule is generated.
        for (const npc of this.npcs.values()) {
            npc.brain?.updateTo(this.now, this);
        }

        // Notify listeners (UI, debug, etc.)
        for (const cb of this._listeners.time) cb(this, mins);

        // Scenes can be time-dependent
        this.sceneManager?.update();
    }

    /**
     * Move player to another location on the world map.
     */
    moveTo(locationId) {
        if (!this.world.locations.has(locationId)) {
            throw new Error(`Unknown location: ${locationId}`);
        }
        if (locationId === this.currentLocationId) return;

        this.currentLocationId = locationId;
        for (const cb of this._listeners.location) cb(this, locationId);

        // When moving, you're typically not inside any specific place
        this.currentPlaceId = null;
        this.currentPlaceKey = null;

        this.sceneManager?.update();
    }

    /**
     * Set where inside the location the player currently is.
     * Use a Place.id, or pass null and set currentPlaceKey to something virtual like "street".
     */
    setCurrentPlace({ placeId = null, placeKey = null } = {}) {
        this.currentPlaceId = placeId;
        this.currentPlaceKey =
            placeKey ?? this._getPlaceKeyById(this.currentLocationId, this.currentPlaceId);
        this.sceneManager?.update();
    }

    // --- Story flags ---
    setFlag(flag, value = true) {
        const key = String(flag);
        if (value) this.flags.add(key);
        else this.flags.delete(key);
        this.sceneManager?.update();
    }
    clearFlag(flag) {
        this.flags.delete(String(flag));
        this.sceneManager?.update();
    }
    hasFlag(flag) {
        return this.flags.has(String(flag));
    }

    // --- Convenience queries used by scenes ---
    getNPCsAtLocation(locationId = this.currentLocationId) {
        const id = String(locationId);
        return this.npcsArray.filter((n) => String(n.locationId) === id);
    }

    /**
     * Wrapper for player actions: do stuff, spend time, log it.
     * This is a good fit for your “choices” later.
     */
    runAction({ label, minutes = 0, apply }) {
        if (typeof label === "string" && label) {
            this.log.push({ t: this.now.toISOString(), label });
        }

        if (typeof apply === "function") {
            // let the action mutate game / player / npcs / world
            apply(this);
        }

        if (minutes > 0) {
            this.advanceMinutes(minutes);
        }
    }

    // --------------------------
    // Scenes (events will use this later)
    // --------------------------
    startScene(scene) {
        this.currentScene = scene;
        for (const cb of this._listeners.scene) cb(this, scene);
    }

    endScene() {
        this.currentScene = null;
        for (const cb of this._listeners.scene) cb(this, null);
    }

    /**
     * Start resolving scenes. Useful for a UI "Start Game" button.
     */
    startGame({ forceSceneId = null } = {}) {
        return this.sceneManager?.start({ forceSceneId });
    }

    // --------------------------
    // Simple event/listener API
    // --------------------------
    /**
     * game.on("time", cb) -> unsubscribe function
     * game.on("location", cb)
     * game.on("scene", cb)
     */
    on(eventName, fn) {
        const set = this._listeners[eventName];
        if (!set) throw new Error(`Unknown event type: ${eventName}`);
        set.add(fn);
        return () => set.delete(fn);
    }

    // --------------------------
    // Save / load
    // --------------------------
    toJSON() {
        return {
            saveVersion: 3,
            seed: this.seed,
            rngState: typeof this.rnd?.getState === "function" ? this.rnd.getState() : null,
            time: this.now.toISOString(),
            world: this.world.toJSON(),
            player: this.player.toJSON(),
            npcs: this.npcsArray.map((npc) => npc.toJSON()),
            homeLocationId: this.homeLocationId,
            homePlaceId: this.homePlaceId,
            currentLocationId: this.currentLocationId,
            currentPlaceId: this.currentPlaceId,
            currentPlaceKey: this.currentPlaceKey,
            flags: [...this.flags],
            log: this.log.map((entry) => ({ ...entry })),
            sceneManager: this.sceneManager?.toJSON?.() ?? null,
        };
    }

    static fromJSON(
        data,
        {
            strings = null,
            scenes = SCENE_DEFS,
            npcTemplates = NPC_REGISTRY,
            traitResolver = null,
        } = {},
    ) {
        if (!data || typeof data !== "object") {
            throw new Error("Game.fromJSON expects a parsed save object");
        }

        const savedStartDate = data?.world?.time?.date ?? data?.time ?? new Date().toISOString();

        // Construct only the runtime shell. Most constructor-generated state is
        // replaced below, and scenes remain stopped until hydration is complete.
        const game = new Game({
            seed: data.seed,
            startDate: new Date(savedStartDate),
            playerOptions: {},
            npcTemplates: [],
            strings,
            scenes,
            defaultSceneId: data?.sceneManager?.defaultSceneId ?? null,
            fallbackSceneId: data?.sceneManager?.fallbackSceneId ?? null,
            autoStartScenes: false,
        });

        if (data.world) {
            game.world = World.fromJSON(data.world, { rnd: game.rnd });
        }

        game.player = Player.fromJSON(data.player || {}, { traitResolver });

        const templates = Array.isArray(npcTemplates) ? npcTemplates : [];
        const findTemplate = (savedNpc) => {
            const registryKey = savedNpc?.meta?.registryKey;
            if (registryKey != null) {
                const byRegistryKey = templates.find(
                    (def) => String(def?.key ?? def?.id ?? "") === String(registryKey),
                );
                if (byRegistryKey) return byRegistryKey;
            }

            return (
                templates.find(
                    (def) => def?.id != null && String(def.id) === String(savedNpc?.id),
                ) ||
                templates.find(
                    (def) => def?.key != null && String(def.key) === String(savedNpc?.id),
                ) ||
                templates.find(
                    (def) => def?.name != null && String(def.name) === String(savedNpc?.name),
                ) ||
                null
            );
        };

        game.npcs = new Map();
        for (const npcData of Array.isArray(data.npcs) ? data.npcs : []) {
            const template = findTemplate(npcData);
            const npc = NPC.fromJSON(npcData, { template, traitResolver });
            const id = String(npc.id || npc.name);
            npc.id = id;
            game.npcs.set(id, npc);
        }

        const hasOwn = (key) => Object.prototype.hasOwnProperty.call(data, key);
        const home = game._findFirstPlaceByKey("player_home");
        game.homeLocationId = hasOwn("homeLocationId")
            ? data.homeLocationId
            : (home?.locationId ?? null);
        game.homePlaceId = hasOwn("homePlaceId") ? data.homePlaceId : (home?.id ?? null);

        game.currentLocationId = hasOwn("currentLocationId")
            ? data.currentLocationId
            : (game.homeLocationId ?? game._pickDefaultLocationId());
        game.currentPlaceId = data.currentPlaceId ?? null;
        game.currentPlaceKey = hasOwn("currentPlaceKey")
            ? data.currentPlaceKey
            : game._getPlaceKeyById(game.currentLocationId, game.currentPlaceId);
        game.flags = new Set(Array.isArray(data.flags) ? data.flags.map(String) : []);
        game.log = Array.isArray(data.log) ? data.log.map((entry) => ({ ...entry })) : [];

        if (data.sceneManager) {
            game.sceneManager.restoreJSON(data.sceneManager);
        } else {
            // Legacy saves did not store scene state. Resolve only after all
            // other state has been restored.
            game.sceneManager.start();
        }

        // Loading itself may have needed random values for backward-compatible
        // fallbacks. Restore the gameplay stream before initializing any legacy
        // NPC brain that was not present in an older save.
        if (data.rngState != null && typeof game.rnd?.setState === "function") {
            game.rnd.setState(data.rngState);
        }
        game._initializeNPCBrains();

        return game;
    }

    _initializeNPCBrains() {
        for (const npc of this.npcs.values()) {
            npc.brain?.initialize(this, this.now);
        }
    }

    _pickDefaultLocationId() {
        const first = this.world.locations.keys().next();
        return first.done ? null : first.value;
    }

    _findFirstPlaceByKey(placeKey) {
        const key = String(placeKey);
        for (const loc of this.world.locations.values()) {
            for (const p of loc.places || []) {
                if (p?.key === key) return p;
            }
        }
        return null;
    }

    _getPlaceKeyById(locationId, placeId) {
        if (!placeId) return null;
        const loc = this.world.getLocation(locationId);
        const place = (loc?.places || []).find((p) => p.id === placeId) || null;
        return place?.key ?? null;
    }

    // --------------------------
    // Internals
    // --------------------------
    _createNPCs(templates) {
        for (const def of templates || []) {
            let npc;
            let id;

            if (def instanceof NPC) {
                npc = def;
                id = def.id || def.name;
            } else {
                npc = new NPC(def);
                id = def.id || npc.id || npc.name;
            }

            // Ensure id is always a string
            id = String(id || npc.name);
            npc.id = id;

            // Keep a stable link to static registry behavior so save files can
            // restore behavior/home naming functions without serializing code.
            if (def && def.key != null && !npc.meta?.registryKey) {
                npc.meta = { ...(npc.meta || {}), registryKey: String(def.key) };
            }

            // Attach home + starting location
            // (legacy) preferLocationsWith -> homePreference.withPlaceCategory
            if (!npc.homePreference && def && Array.isArray(def.preferLocationsWith)) {
                npc.homePreference = { withPlaceCategory: def.preferLocationsWith };
            }
            this._assignHomeForNPC(id, npc);

            this.npcs.set(id, npc);
        }
    }

    /**
     * Assign a unique home Location + create a unique home Place for an NPC
     * based on npc.homePreference.
     *
     * homePreference supports selecting ONE strategy at random from:
     *  - withKey: pick random location that already contains any Place.key in the list
     *  - withPlaceCategory: pick location with the most places whose props.category matches any tag
     *  - withLocationCategory: pick location with the most location.tags matches
     *
     * nameFn(chosenLocation) is used to name the created home Place.
     */
    _assignHomeForNPC(id, npc) {
        const pref = npc?.homePreference;
        if (!pref) {
            throw new Error(`NPC '${id}' has no homePreference`);
        }

        const strategies = [];
        if (Array.isArray(pref.withKey) && pref.withKey.length) {
            strategies.push({ kind: "withKey", values: pref.withKey });
        }
        if (Array.isArray(pref.withPlaceCategory) && pref.withPlaceCategory.length) {
            strategies.push({ kind: "withPlaceCategory", values: pref.withPlaceCategory });
        }
        if (Array.isArray(pref.withLocationCategory) && pref.withLocationCategory.length) {
            strategies.push({ kind: "withLocationCategory", values: pref.withLocationCategory });
        }

        if (!strategies.length) {
            throw new Error(
                `homePreference for NPC '${id}' must include at least one of withKey, withPlaceCategory, withLocationCategory`,
            );
        }

        const pick = strategies[(this.rnd() * strategies.length) | 0];
        const allLocations = [...this.world.locations.values()];
        if (!allLocations.length) throw new Error("World has no locations");

        const pickRandom = (arr) => arr[(this.rnd() * arr.length) | 0];

        const placeHasAnyCategory = (place, wantedSet) => {
            const cat = place?.props?.category;
            if (!cat) return false;
            const cats = Array.isArray(cat) ? cat : [cat];
            for (const c of cats) if (wantedSet.has(c)) return true;
            return false;
        };

        let chosenLocation = null;

        if (pick.kind === "withKey") {
            const wantedKeys = new Set(pick.values.map(String));
            const candidates = allLocations.filter((loc) =>
                (loc.places || []).some((p) => wantedKeys.has(String(p.key))),
            );
            if (!candidates.length) {
                throw new Error(
                    `No location contains any place with key in [${[...wantedKeys].join(", ")}]`,
                );
            }
            chosenLocation = pickRandom(candidates);
        }

        if (pick.kind === "withPlaceCategory") {
            const wanted = new Set(pick.values);
            let bestScore = -1;
            let best = [];

            for (const loc of allLocations) {
                let score = 0;
                for (const pl of loc.places || []) {
                    if (placeHasAnyCategory(pl, wanted)) score++;
                }

                if (score > bestScore) {
                    bestScore = score;
                    best = [loc];
                } else if (score === bestScore) {
                    best.push(loc);
                }
            }

            if (bestScore <= 0) {
                throw new Error(
                    `No location has any places with category in [${[...wanted].join(", ")}]`,
                );
            }
            chosenLocation = pickRandom(best);
        }

        if (pick.kind === "withLocationCategory") {
            const wanted = new Set(pick.values);
            let bestScore = -1;
            let best = [];

            for (const loc of allLocations) {
                const tags = Array.isArray(loc.tags) ? loc.tags : [];
                let score = 0;
                for (const t of tags) if (wanted.has(t)) score++;

                if (score > bestScore) {
                    bestScore = score;
                    best = [loc];
                } else if (score === bestScore) {
                    best.push(loc);
                }
            }

            if (bestScore <= 0) {
                throw new Error(`No location has any tags in [${[...wanted].join(", ")}]`);
            }
            chosenLocation = pickRandom(best);
        }

        if (!chosenLocation) {
            throw new Error(`Failed to choose a home location for NPC '${id}'`);
        }

        // Create a unique home Place at the chosen location
        const homeId = `home_${id}`;
        const displayName =
            typeof pref.nameFn === "function" ? pref.nameFn(chosenLocation) : `${npc.name}'s home`;

        const homePlace = this.world.createPlaceAt(
            {
                id: homeId,
                key: homeId,
                name: displayName,
                props: {
                    category: [PLACE_TAGS.housing],
                    ownerNpcId: id,
                    isResidence: true,
                    discovered: false,
                    icon: "🏠",
                },
            },
            chosenLocation.id,
        );

        npc.homeLocationId = String(chosenLocation.id);
        npc.homePlaceId = homePlace ? homePlace.id : homeId;

        // Start NPC at home by default
        if (!npc.locationId) {
            npc.setLocationAndPlace(String(chosenLocation.id), npc.homePlaceId);
        }
    }
}
