export const CINEMA_GENRES = Object.freeze({
  action: "Action",
  adventure: "Adventure",
  animation: "Animation",
  comedy: "Comedy",
  "coming-of-age": "Coming-of-age",
  crime: "Crime",
  documentary: "Documentary",
  drama: "Drama",
  family: "Family",
  fantasy: "Fantasy",
  foreign: "Foreign",
  historical: "Historical",
  horror: "Horror",
  musical: "Musical",
  mystery: "Mystery",
  "political-thriller": "Political thriller",
  romance: "Romance",
  "romantic-comedy": "Romantic comedy",
  "science-fiction": "Science fiction",
  sports: "Sports",
  supernatural: "Supernatural",
  thriller: "Thriller",
  western: "Western",
});

const GENRE_IDS_BY_LABEL = Object.freeze(
  Object.fromEntries(
    Object.entries(CINEMA_GENRES).map(([id, label]) => [label, id]),
  ),
);

const MOVIES = [
  { id: "after-the-last-train", title: "The Mess", genre: "Drama", durationMinutes: 112 },
  { id: "all-the-small-orbits", title: "Star Walks", genre: "Science fiction", durationMinutes: 126 },
  { id: "amber-house", title: "Inherited", genre: "Horror", durationMinutes: 98 },
  { id: "april-in-reverse", title: "Me, You and Tulouse", genre: "Romance", durationMinutes: 105 },
  { id: "beneath-glass-water", title: "Death on the Nile Express", genre: "Mystery", durationMinutes: 119 },
  { id: "borrowed-summer", title: "Kosciuszko Gunpowder", genre: "Coming-of-age", durationMinutes: 101 },
  { id: "brass-and-thunder", title: "Quick and Quarreling V: The Return", genre: "Action", durationMinutes: 134 },
  { id: "bright-little-disasters", title: "Engagement Busters", genre: "Comedy", durationMinutes: 94 },
  { id: "city-of-paper-birds", title: "Down.", genre: "Animation", durationMinutes: 89 },
  { id: "cold-harbour", title: "Engine Town", genre: "Crime", durationMinutes: 121 },
  { id: "constant-signal", title: "Gigant: A Carter Experiment", genre: "Science fiction", durationMinutes: 116 },
  { id: "dancing-at-closing-time", title: "Eviction", genre: "Musical", durationMinutes: 108 },
  { id: "dead-air", title: "82 Days Earlier", genre: "Horror", durationMinutes: 103 },
  { id: "dust-on-the-crown", title: "Salieri", genre: "Historical", durationMinutes: 142 },
  { id: "eight-minutes-to-morning", title: "Found Fellow", genre: "Thriller", durationMinutes: 110 },
  { id: "every-road-home", title: "Find Me If You Dare", genre: "Drama", durationMinutes: 124 },
  { id: "featherweight", title: "Contenders", genre: "Sports", durationMinutes: 107 },
  { id: "fire-escape-season", title: "Noon in Barcelona", genre: "Romance", durationMinutes: 99 },
  { id: "ghosts-of-the-boardwalk", title: "The Summoning: Final Cut", genre: "Supernatural", durationMinutes: 115 },
  { id: "good-dogs-of-war", title: "S.M.A.S.H: The Movie", genre: "Comedy", durationMinutes: 96 },
  { id: "gravity-club", title: "Brotherhood of the around-the-world Tie", genre: "Adventure", durationMinutes: 128 },
  { id: "half-past-never", title: "Path to Perinthia", genre: "Fantasy", durationMinutes: 117 },
  { id: "hollow-valentine", title: "They Die", genre: "Horror", durationMinutes: 100 },
  { id: "hotel-aurora", title: "Fornication Action", genre: "Foreign", durationMinutes: 109 },
  { id: "how-to-steal-a-moon", title: "The Cousin Caper", genre: "Family", durationMinutes: 92 },
  { id: "invisible-choir", title: "The Ugliest Girl On The Planet", genre: "Documentary", durationMinutes: 87 },
  { id: "ironwood", title: "Dreamy Valley", genre: "Fantasy", durationMinutes: 138 },
  { id: "june-zero", title: "The Mercurian", genre: "Science fiction", durationMinutes: 123 },
  { id: "kingdom-of-moths", title: "Burned II", genre: "Animation", durationMinutes: 91 },
  { id: "last-light-at-low-tide", title: "Sunlight", genre: "Drama", durationMinutes: 114 },
  { id: "little-acts-of-treason", title: "Yesterday It Was Just Us", genre: "Political thriller", durationMinutes: 131 },
  { id: "marble-sky", title: "Dig", genre: "Adventure", durationMinutes: 120 },
  { id: "midnight-delivery", title: "House Free 3: A Night in London", genre: "Comedy", durationMinutes: 97 },
  { id: "museum-of-rain", title: "After Dawn", genre: "Romance", durationMinutes: 111 },
  { id: "northbound", title: "E-mails to W", genre: "Foreign", durationMinutes: 118 },
  { id: "one-hundred-doors", title: "Blades Drawn 2", genre: "Mystery", durationMinutes: 106 },
  { id: "orchard-at-the-end", title: "Keepsake", genre: "Drama", durationMinutes: 127 },
  { id: "painted-wolves", title: "Disaster Daisy", genre: "Western", durationMinutes: 125 },
  { id: "perfect-alibi", title: "Every Wrong Choice", genre: "Crime", durationMinutes: 104 },
  { id: "quiet-giants", title: "Can You See Anything?", genre: "Documentary", durationMinutes: 90 },
  { id: "red-comet-cafe", title: "Find a Girl in 10 days (Foolproof!)", genre: "Romantic comedy", durationMinutes: 102 },
  { id: "salt-king", title: "Bolesław I the Brave", genre: "Historical", durationMinutes: 145 },
  { id: "second-sunrise", title: "Nikki 13", genre: "Science fiction", durationMinutes: 129 },
  { id: "seven-bells", title: "The Color Red", genre: "Supernatural", durationMinutes: 113 },
  { id: "soft-targets", title: "Paul Blart: Mall Cop 2", genre: "Action", durationMinutes: 122 },
  { id: "static-between-us", title: "Mechanic Wishes", genre: "Romance", durationMinutes: 108 },
  { id: "summer-circuit", title: "Vespa vs Volkswagen", genre: "Sports", durationMinutes: 103 },
  { id: "violet-hour", title: "The Blue Kilometer", genre: "Thriller", durationMinutes: 117 },
  { id: "we-were-volcanoes", title: "Enact Vengeance", genre: "Coming-of-age", durationMinutes: 109 },
  { id: "winter-arcade", title: "Good Grandma", genre: "Comedy", durationMinutes: 95 },
];

export const CINEMA_MOVIES = Object.freeze(MOVIES.map((movie) => {
  const genreId = GENRE_IDS_BY_LABEL[movie.genre];
  if (!genreId) throw new Error(`Cinema movie '${movie.id}' has an unknown genre`);
  return Object.freeze({ ...movie, genreId });
}));
